from enum import StrEnum


class Role(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    AGENCY_ADMIN = "AGENCY_ADMIN"
    STRATEGIST = "STRATEGIST"
    CONTENT_EDITOR = "CONTENT_EDITOR"
    DESIGNER = "DESIGNER"
    CLIENT_OWNER = "CLIENT_OWNER"
    CLIENT_REVIEWER = "CLIENT_REVIEWER"
    VIEWER = "VIEWER"


class ContentStatus(StrEnum):
    DRAFT = "DRAFT"
    INTERNAL_REVIEW = "INTERNAL_REVIEW"
    CLIENT_REVIEW = "CLIENT_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class ApprovalStage(StrEnum):
    CLIENT = "CLIENT"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

